import { Moon, Sun, X } from 'lucide-react'
import { useState } from 'react'
import type { AzuremindVersion } from '../types'
import { DeveloperAccessPanel } from './DeveloperAccessPanel'

type Props = { darkMode: boolean; defaultModel: AzuremindVersion; systemPrompt: string; onDarkModeChange: (value: boolean) => void; onDefaultModelChange: (value: AzuremindVersion) => void; onSystemPromptChange: (value: string) => void; onClose: () => void }

export function SettingsPanel({ darkMode, defaultModel, systemPrompt, onDarkModeChange, onDefaultModelChange, onSystemPromptChange, onClose }: Props) {
  const defaultBeta = ['chopp2979@inst.hcpss.org']
  const defaultDevelopers = ['owall4229@inst.hcpss.org']
  const [style, setStyle] = useState<'classic' | 'modern'>((localStorage.getItem('cobalt-style') as 'classic' | 'modern') || 'classic')
  const [accessOpen, setAccessOpen] = useState(false)
  const [betaEmails, setBetaEmails] = useState<string[]>(JSON.parse(localStorage.getItem('cobalt-beta-testers') || JSON.stringify(defaultBeta)))
  const [developerEmails, setDeveloperEmails] = useState<string[]>(JSON.parse(localStorage.getItem('cobalt-developers') || JSON.stringify(defaultDevelopers)))
  const isDeveloper = developerEmails.includes((JSON.parse(localStorage.getItem('azuremind-account') || 'null')?.email || '').toLowerCase())
  const changeStyle = (value: 'classic' | 'modern') => { setStyle(value); localStorage.setItem('cobalt-style', value); document.body.dataset.style = value; window.dispatchEvent(new Event('cobalt-style-changed')) }
  const addEmail = (kind: 'beta' | 'developer', email: string) => { const normalized = email.trim().toLowerCase(); if (!normalized.includes('@')) return; const setter = kind === 'beta' ? setBetaEmails : setDeveloperEmails; setter((current) => current.includes(normalized) ? current : [...current, normalized]); localStorage.setItem(kind === 'beta' ? 'cobalt-beta-testers' : 'cobalt-developers', JSON.stringify([...(kind === 'beta' ? betaEmails : developerEmails), normalized])); window.dispatchEvent(new Event('cobalt-access-changed')) }
  const removeEmail = (kind: 'beta' | 'developer', email: string) => { const setter = kind === 'beta' ? setBetaEmails : setDeveloperEmails; setter((current) => current.filter((entry) => entry !== email)); localStorage.setItem(kind === 'beta' ? 'cobalt-beta-testers' : 'cobalt-developers', JSON.stringify((kind === 'beta' ? betaEmails : developerEmails).filter((entry) => entry !== email))); window.dispatchEvent(new Event('cobalt-access-changed')) }
  if (accessOpen) return <DeveloperAccessPanel betaEmails={betaEmails} developerEmails={developerEmails} onAdd={addEmail} onRemove={removeEmail} onClose={() => setAccessOpen(false)} />
  return <div className="modal-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose() }}><section className="settings-modal" role="dialog" aria-modal="true" aria-labelledby="settings-title"><button className="modal-close" onClick={onClose} title="Close"><X size={17} /></button><div className="modal-kicker">COBALT AI CONFIGURATION</div><h2 id="settings-title">Workspace settings</h2><p className="modal-copy">Personalize this workspace. Changes are saved locally for this browser.</p><label className="modal-field">Interface style<select value={style} onChange={(event) => changeStyle(event.target.value as 'classic' | 'modern')}><option value="classic">Classic</option><option value="modern">Modern</option></select></label><label className="setting-toggle"><span><strong>Dark mode</strong><small>Use a low-glare workspace theme</small></span><button onClick={() => onDarkModeChange(!darkMode)} aria-pressed={darkMode} className={darkMode ? 'on' : ''}>{darkMode ? <Moon size={14} /> : <Sun size={14} />}</button></label><label className="modal-field">Default model<select value={defaultModel} onChange={(event) => onDefaultModelChange(event.target.value as AzuremindVersion)}><option value="1.0">Cobalt AI 1.0</option><option value="1.1">Cobalt AI 1.1</option><option value="1.2">Cobalt AI 1.2</option><option value="2.0">Cobalt AI 2.0</option><option value="dev">Cobalt AI Dev</option></select></label><label className="modal-field">Additional system prompt<textarea value={systemPrompt} onChange={(event) => onSystemPromptChange(event.target.value)} placeholder="Add workspace-specific guidance..." rows={5} /></label>{isDeveloper && <button className="developer-access-button" onClick={() => setAccessOpen(true)}>Manage beta testers and developers</button>}<button className="modal-submit" onClick={onClose}>Done <span>→</span></button></section></div>
}
