import { Bell, ChevronLeft, ChevronRight, Code2, CircleHelp, MessageSquarePlus, Settings2, Trash2, UserCircle } from 'lucide-react'
import { useState } from 'react'
import type { Conversation } from '../types'

type Props = { conversations: Conversation[]; activeId: string; apiKey?: string; onApiKeyChange?: (value: string) => void; onNewChat: () => void; onSelectChat: (id: string) => void; onDeleteChat: (id: string) => void; onClearHistory: () => void; product: 'chat' | 'code'; onProductChange: (product: 'chat' | 'code') => void }

export function Sidebar({ conversations, activeId, onNewChat, onSelectChat, onDeleteChat, onClearHistory, product, onProductChange }: Props) {
  const [collapsed, setCollapsed] = useState(false)
  const action = (type: 'profile' | 'settings' | 'notifications' | 'help') => { if (type === 'profile') document.querySelector<HTMLButtonElement>('.user-chip')?.click(); else if (type === 'settings') document.querySelector<HTMLButtonElement>('[title="Workspace settings"]')?.click(); else window.alert(type === 'notifications' ? 'You have no new notifications.' : 'Cobalt AI is ready. Use the composer to chat, attach files, or create an image.') }
  return <aside className={`sidebar ${collapsed ? 'collapsed' : ''}`}><div className="brand"><div className="brand-mark cobalt-mark" onClick={() => setCollapsed(!collapsed)} title={collapsed ? 'Expand navigation' : 'Collapse navigation'}>{collapsed ? <ChevronRight size={17} /> : <>C<span /></>}</div>{!collapsed && <div><strong>Cobalt AI</strong><small>Workspace</small></div>}</div>{!collapsed && <><button className={`product-switch ${product === 'chat' ? 'active' : ''}`} onClick={() => onProductChange('chat')}><span className="product-icon cobalt-mark small">C<span /></span><span><strong>Cobalt AI</strong><small>Chat workspace</small></span></button><button className={`product-switch ${product === 'code' ? 'active' : ''}`} onClick={() => onProductChange('code')}><span className="product-icon code-mark"><Code2 size={15} /></span><span><strong>Cobalt Code</strong><small>Developer workspace</small></span></button><button className="new-chat" onClick={onNewChat}><MessageSquarePlus size={17} /> New conversation</button><div className="side-section history-section"><div className="section-heading"><span>Recent conversations</span><span className="count">{conversations.length}</span></div><div className="conversation-list">{conversations.length === 0 && <p className="empty-history">No conversations yet.</p>}{conversations.map((conversation) => <div className={`conversation-row ${conversation.id === activeId ? 'active' : ''}`} key={conversation.id}><button className="conversation-item" onClick={() => onSelectChat(conversation.id)}><MessageSquarePlus size={14} /><span>{conversation.title}</span><small>{conversation.updatedAt}</small></button><button className="delete-chat" title={`Delete ${conversation.title}`} onClick={() => onDeleteChat(conversation.id)}><Trash2 size={13} /></button></div>)}</div></div></>}<div className="sidebar-bottom"><button className="side-action" onClick={() => action('profile')} title="Profile"><UserCircle size={16} /><span>Profile</span></button><button className="side-action" onClick={() => action('notifications')} title="Notifications"><Bell size={16} /><span>Notifications</span></button><button className="side-action" onClick={() => action('settings')} title="Settings"><Settings2 size={16} /><span>Settings</span></button><button className="side-action" onClick={() => action('help')} title="Help"><CircleHelp size={16} /><span>Help</span></button>{!collapsed && <button className="side-action danger" onClick={onClearHistory}><Trash2 size={16} /><span>Clear chat history</span></button>}{!collapsed && <button className="collapse-action" onClick={() => setCollapsed(true)}><ChevronLeft size={16} /> Collapse navigation</button>}</div></aside>
}
